### ISSUE TITLE
Worth it as a New track? Typescriptlang

### ISSUE THREAD

**Issue by masters3d** [exercism/xcoffeescript#42]
http://www.typescriptlang.org

Superset of JavaScript bridging the gap to  EcmaScript 6 suggested features. 

I know this is what CoffeeScript is trying to do. I just wanted to see what you thoughts were on this.

**Comment by kytrinyx** [comment]
I'm open to it, want me to create a repo for it?

**Comment by masters3d** [comment]
Lets wait to see what the final EcmaScript 6 spec looks like by the end of year. (June 2015 release )  [1]
https://github.com/exercism/xecmascript

I think Typescriptlang and EcmaScript 6 may be really close to the same lang by then. 

 [1]  http://www.2ality.com/2014/06/es6-schedule.html

**Comment by kytrinyx** [comment]
Cool, I did start a repo for ecmascript, maybe we can just use that when the time comes.
